version: 2
updates: 
  - package-ecosystem: "npm" 
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
    rebase-strategy: "disabled"
    open-pull-requests-limit: 6

  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
    rebase-strategy: "disabled"
    open-pull-requests-limit: 2

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
    rebase-strategy: "disabled"
    open-pull-requests-limit: 2
