name: Practical Email Management

on:
  workflow_dispatch:
    inputs:
      target:
        description: 'Target'
        required: true


jobs:
  initialize:
    name: Initialize
    runs-on: ubuntu-latest
    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.12.1
        with:
          access_token: ${{ github.token }}
      - name: Print all github variables
        run: echo "$JSON"
        env:
          JSON: ${{ toJson(github) }}
